### ISSUE TITLE
Code Please

### ISSUE THREAD

**Issue by yucc-leon** [lxing532/Dialogue-Topic-Segmenter#2]
![image](https://user-images.githubusercontent.com/17897916/139061201-0466cd0b-3b76-4739-bd0a-383dff31f84d.png)
Hi, your work seems quite promising but the code and model can't be found here. So will there be any updating?

**Comment by JacksonMaxfield** [comment]
Agreed. Please add the code.

**Comment by Mrwangkedong** [comment]
放代码只是说说？
